[Wends] [Add] GET functions for api/testimonies, api/projects, and api/events
caspted/se-webapp pull request #3
Opened 2024-06-14 15:52 UTC by wends05

Added api routes for api/testimonites, api/project, and api/events.
Function implemented fetches all documents in the corresponding collection in the Firestore Database.

2024-06-15 15:24 UTC, caspted requested changes
For each function, its better to have a specific naming convention to as to not cause conflicts later on in development. It is also best practice to make better code documentation. This is usually what is used for Node.js and Express but for Next.js its not case . So good job on the task!


- Change the firebase file name to firebaseConfig.ts to avoid merge conflict with AJ's branch.

2024-06-15 15:31 UTC, ajaparicio36 commented
> For each function, its better to have a specific naming convention to as to not cause conflicts later on in development. It is also best practice to make better code documentation.
> 
> * Change the name of the functions to something like getEvents, getProjects, and getTestimonies.
> 
> -Change the firebase file name to firebaseConfig.ts to avoid merge conflict with AJ's branch.

Hmm, yes it's good but doesn't Next.js require those function names as its default for backend routes?
Impressive code, by the way! 

Though for commits 
- I do recommend to separate it for files if you want to be more specific on the commit messages.
- It's okay, though, the code isn't relatively too long to need separate commit messages
- Don't be afraid to have many commits though!

2024-06-17 12:16 UTC, jedmamosto approved these changes
Approved! Logic-wise its correct na man (i think HAHHAAH) we'll find out once we have the frontend integration but ig for now its fine to merge

Just resolve the change request by @caspted for the firebase config file and ur good to go

gj wends!

2024-06-17 15:42 UTC, ajaparicio36 approved these changes
Yup, very good code!

2024-06-17 15:42 UTC, ajaparicio36 commented on app/api/events/route.ts
I'd say it's up to @caspted for this, but maybe we should use NextRequest and NextResponse types since we're using Next.js, but it depends on what we decide, ultimately we should decide to use either regular HTTP types or Next types so that we have more similar code.

2024-06-17 15:42 UTC, ajaparicio36 commented on app/api/projects/route.ts
I don't think it's necessary to put any as the type for error, TypeScript should automatically infer types for the try/catch blocks.

2024-06-18 02:15 UTC, wends05 commented
Thank you manongs, I will be changing the code nalang based on the comments

2024-06-21 08:17 UTC, wends05 commented on app/api/projects/route.ts
Hello nong, ga error siya galing on line 11 if i remove the type annotation. It says (Argument of type 'unknown' is not assignable to parameter of type 'BodyInit | null | undefined'.)

2024-06-21 10:24 UTC, wends05 commented on app/api/events/route.ts
Nong Teddie @caspted agreed to use Next types for consistency.

2024-06-21 13:08 UTC, caspted commented on app/api/projects/route.ts
Here is another solution gali if you want to remove the error for the type annotation you can use this
} catch (err) {
    const errorMessage = err instanceof Error ? err.message : 'Internal Server Error';
    return new NextResponse(errorMessage, { status: 500 });
}

2024-06-21 13:22 UTC, wends05 commented on app/api/projects/route.ts
Sige nong, noted

2024-06-21 13:37 UTC, caspted approved these changes
Looks goods na,  Good job!

2024-06-21 13:37 UTC, caspted approved these changes
Looks goods na,  Good job!

2024-06-21 13:42 UTC, merged